"use strict";
const SYS=`You are helping a Sigma Chi chapter executive team consolidate each officer's individual strategic-planning homework into shared themes for the team leader.
Rules: merge items that mean the same thing and keep genuinely distinct ideas separate. Write in plain, concise language a college chapter officer would use. Never invent ideas no participant expressed. Every output item lists "refs": the exact ref strings of the source items it was built from (copy them exactly). Order each list from most to least widely shared.`;
const SHAPES={
  m1:`Return JSON: {"strengths":[{"theme":"short theme","detail":"one sentence","refs":[]}],"problems":[same],"opportunities":[same],"threats":[same],"impact":"3-4 sentence synthesis of what the SPOT analysis means for how the chapter operates","focusAreas":[{"area":"short name","why":"one or two sentences combining participants' reasons","refs":["P1-f1"]}]}. Focus areas may also draw refs from SPOT items when an item clearly argues for that area, but prefer f-refs.`,
  m2:`Return JSON: {"imperatives":[{"title":"imperative written as a commitment, e.g. 'We commit to...'","area":"the id of the Expect More area or goal it advances, from expectMoreAreas (e.g. 'dev' or 'dev:1'); follow participants' own 'area' choices where they agree, otherwise pick the best fit","refs":["P1-r1"],"goals":[{"text":"goal rewritten to be SMART where possible, keeping the participant's intent","note":"what, if anything, still needs to be defined to make it SMART (empty string if nothing)"}]}],"imp1Goals":[{"text":"SMART goal under the required Imperative 1","refs":["P1-g1"],"note":""}],"observations":"one or two sentences on where the team agrees and where it's split"}. Each imperative cluster must include every r-ref that belongs to it. Give up to 4 goals per imperative, merging duplicates.`,
  m3:`Return JSON: {"keyPoints":[{"point":"one sentence","refs":[]}],"why":"a 120-180 word 'Our Why' statement in the team's collective voice (we/our), built only from what participants wrote","middle":[{"idea":"one practical idea","refs":[]}]}`,
  m4:`Return JSON: {"conversation":"2-3 sentence summary","operationalize":"2-3 sentence summary","resistance":"2-3 sentence summary including the strategies offered","arena":"2-3 sentence summary of how officers intend to dare greatly","dare":[{"idea":"one practical idea","refs":[]}],"revisions":["specific revision to the strategic plan suggested by the feedback, if any"]}`,
  m5:`Return JSON: {"challenges":[{"point":"one sentence","refs":[]}],"wins":[{"point":"one sentence","refs":[]}],"resources":[{"point":"a resource the team needs","refs":[]}],"summary":"2-3 sentence summary for the leader"}`
};
module.exports = { SYS, SHAPES };
